# This file was generated by GoReleaser. DO NOT EDIT.
cask "gale" do
  name "gale"
  desc "Self-hosted GitHub Actions runner manager with auto-scaling"
  homepage "https://github.com/manashmandal/gale"
  version "2025.12.27"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gale"

  on_macos do
    on_intel do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_darwin_amd64.tar.gz"
      sha256 "542957f5c69447ad1abd6877630c7ecac24aba6cef5ca531f48ee8dcce897e16"
    end
    on_arm do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_darwin_arm64.tar.gz"
      sha256 "1d311b0c8ea5c03447e5c8d6f99ac7145947c2f45a42af8cd806dacca7f188bd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_linux_amd64.tar.gz"
      sha256 "33226f41f818aaf998178f0714e6f8655c44ff8e386fa6f3aefdfd44fb5ba5f3"
    end
    on_arm do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_linux_arm64.tar.gz"
      sha256 "8d4631f3fd51d4222ab9a402ea27fd89196642278f384c16bb85359945644747"
    end
  end

  caveats do
    "To get started:"
    "  gale init     # Interactive setup"
    "  gale start    # Start the autoscaler"
  end

  # No zap stanza required
end
