# This file was generated by GoReleaser. DO NOT EDIT.
cask "gale" do
  name "gale"
  desc "Self-hosted GitHub Actions runner manager with auto-scaling"
  homepage "https://github.com/manashmandal/gale"
  version "2025.1227.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gale"

  on_macos do
    on_intel do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_darwin_amd64.tar.gz"
      sha256 "ebad7d9be1c4a283a17f1ef0bb5924fb446a449a926c371bd89e998ee69b5bb1"
    end
    on_arm do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_darwin_arm64.tar.gz"
      sha256 "1c396bc9e7e08b8da85a18ff5fa144f6785057d7758b53c9c9b2c6deba90d055"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_linux_amd64.tar.gz"
      sha256 "c47a47ee8a988953058f61fc4a779962ff770013c2402560702e295d80d818fc"
    end
    on_arm do
      url "https://github.com/manashmandal/gale/releases/download/v#{version}/gale_#{version}_linux_arm64.tar.gz"
      sha256 "8bb0eca5cc751f023e31db360da3d31d01c6696f36447d94fd384ea47e9375f7"
    end
  end

  caveats do
    "To get started:"
    "  gale init     # Interactive setup"
    "  gale start    # Start the autoscaler"
  end

  # No zap stanza required
end
