# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imggen < Formula
  desc "CLI tool for generating images using AI image generation APIs"
  homepage "https://github.com/manashmandal/imggen"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manashmandal/imggen/releases/download/v0.0.3/imggen_0.0.3_darwin_amd64.tar.gz"
      sha256 "49e0955c8deb919a4e2ad4b5372600dcbf846babf4aa31f7f08d59271a413b75"

      def install
        bin.install "imggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manashmandal/imggen/releases/download/v0.0.3/imggen_0.0.3_darwin_arm64.tar.gz"
      sha256 "4abdcda1a55d381f240c1499930832142647d42c3a10c51dd093d41cbfa02014"

      def install
        bin.install "imggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/manashmandal/imggen/releases/download/v0.0.3/imggen_0.0.3_linux_amd64.tar.gz"
      sha256 "8b7ccd6c9ce13f8512269422edef3716910191c66d5a3c678b02fa2f89b7cad3"
      def install
        bin.install "imggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manashmandal/imggen/releases/download/v0.0.3/imggen_0.0.3_linux_arm64.tar.gz"
      sha256 "176148c78b296ca4bf319012d1f477fcf30a11fb17686a4d77dca0fe31f42a83"
      def install
        bin.install "imggen"
      end
    end
  end

  test do
    system "#{bin}/imggen", "--version"
  end
end
