# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imggen < Formula
  desc "CLI tool for generating images using AI image generation APIs"
  homepage "https://github.com/manashmandal/imggen"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manashmandal/imggen/releases/download/v0.1.1/imggen_0.1.1_darwin_amd64.tar.gz"
      sha256 "3175049762fb9894719d47a4c3f7c2cb7493b43208d893e60dd9d4289df13b19"

      def install
        bin.install "imggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manashmandal/imggen/releases/download/v0.1.1/imggen_0.1.1_darwin_arm64.tar.gz"
      sha256 "237d29c0c485da6c1d260510797cfbe2ed982f3b462cef770cc546b9e4483227"

      def install
        bin.install "imggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/manashmandal/imggen/releases/download/v0.1.1/imggen_0.1.1_linux_amd64.tar.gz"
      sha256 "71c078d8baf32fa49543faf2587586cbc87b99bd7b33919c59c8c5e4370374ad"
      def install
        bin.install "imggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manashmandal/imggen/releases/download/v0.1.1/imggen_0.1.1_linux_arm64.tar.gz"
      sha256 "a8d5a9e8da1878dba0806cc5fe3fad138ab17f161da33e1a2d22e0076779cc7b"
      def install
        bin.install "imggen"
      end
    end
  end

  test do
    system "#{bin}/imggen", "--version"
  end
end
